on:
  workflow_dispatch:
 
jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_SSH_KEY: ${{ secrets.SSH_KEY }}
          MY_SSH_HOST: ${{ secrets.SSH_HOST }}
          MY_SSH_USER: ${{ secrets.SSH_USER }}
          MY_ENV_FILE: ${{ secrets.ENV_FILE }}
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          MY_OPENSSL_ITER: ${{ secrets.MY_OPENSSL_ITER }}
        run: |
          echo "MY_SSH_KEY (***)     = ${MY_SSH_KEY}"
          echo "MY_SSH_KEY (openssl) = $(echo "${MY_SSH_KEY}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "MY_SSH_HOST (***)     = ${MY_SSH_HOST}"
          echo "MY_SSH_HOST (openssl) = $(echo "${MY_SSH_HOST}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "MY_SSH_USER (***)     = ${MY_SSH_USER}"
          echo "MY_SSH_USER (openssl) = $(echo "${MY_SSH_USER}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "MY_ENV_FILE (***)     = ${MY_ENV_FILE}"
          echo "MY_ENV_FILE (openssl) = $(echo "${MY_ENV_FILE}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
